<?php

/**
 * @file
 * Helfi_hakuvahti.
 *
 *  Helfi_hakuvahti.module.
 */

declare(strict_types=1);

/**
 * UHF-12723: Move configuration from rekry to hakuvahti module.
 */
function helfi_hakuvahti_update_11001(): void {
  \Drupal::configFactory()->getEditable('helfi_hakuvahti.settings')
    ->set('hakuvahti_tos_link_url', '')
    ->set('hakuvahti_instructions_link_url', '')
    ->set('langcode', 'en')
    ->save();
}
